# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1716, 1024)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("\n"
"QMainWindow{\n"
"    color: #F0EBEB;\n"
"    background-color: rgb(43, 43, 57);\n"
"}\n"
"\n"
"QStatusBar{\n"
"    color: #F0EBEB;\n"
"}")
        self.generalWigdet = QtWidgets.QWidget(MainWindow)
        self.generalWigdet.setStyleSheet("QWidget{\n"
"    color: #F0EBEB;\n"
"    background-color: rgb(19, 19, 26);\n"
"}")
        self.generalWigdet.setObjectName("generalWigdet")
        self.title = QtWidgets.QLabel(self.generalWigdet)
        self.title.setGeometry(QtCore.QRect(690, 20, 151, 41))
        self.title.setMinimumSize(QtCore.QSize(0, 13))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.title.setStyleSheet("color: rgb(255, 255, 255);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setIndent(0)
        self.title.setObjectName("title")
        self.canvas = QtWidgets.QWidget(self.generalWigdet)
        self.canvas.setGeometry(QtCore.QRect(60, 130, 1351, 631))
        self.canvas.setStyleSheet("background: #F0EBEB;\n"
"background-image: url(:/cct/grafosback.png);\n"
"border-radius: 30px;\n"
"background-repeat: no-repeat;")
        self.canvas.setObjectName("canvas")
        self.cleanAll = QtWidgets.QPushButton(self.generalWigdet)
        self.cleanAll.setGeometry(QtCore.QRect(1480, 580, 131, 21))
        self.cleanAll.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: red;\n"
"    border-left: 10px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: white;\n"
"    color: #13131A\n"
"}\n"
"")
        self.cleanAll.setObjectName("cleanAll")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.generalWigdet)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1470, 250, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addVertex = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addVertex.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: red;\n"
"    border-left: 10px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: white;\n"
"    color: #13131A\n"
"}\n"
"\n"
"")
        self.addVertex.setObjectName("addVertex")
        self.verticalLayout_2.addWidget(self.addVertex)
        self.delVertex = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delVertex.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: red;\n"
"    border-left: 10px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: white;\n"
"    color: #13131A\n"
"}\n"
"")
        self.delVertex.setObjectName("delVertex")
        self.verticalLayout_2.addWidget(self.delVertex)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.generalWigdet)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1470, 470, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addEdge = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.addEdge.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: red;\n"
"    border-left: 10px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: white;\n"
"    color: #13131A\n"
"}\n"
"")
        self.addEdge.setObjectName("addEdge")
        self.verticalLayout_3.addWidget(self.addEdge)
        self.delEdge = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.delEdge.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: red;\n"
"    border-left: 10px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: white;\n"
"    color: #13131A\n"
"}\n"
"")
        self.delEdge.setObjectName("delEdge")
        self.verticalLayout_3.addWidget(self.delEdge)
        self.subtitle_edge = QtWidgets.QLabel(self.generalWigdet)
        self.subtitle_edge.setGeometry(QtCore.QRect(1450, 410, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        self.subtitle_edge.setFont(font)
        self.subtitle_edge.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle_edge.setObjectName("subtitle_edge")
        self.subtitle_vertex = QtWidgets.QLabel(self.generalWigdet)
        self.subtitle_vertex.setGeometry(QtCore.QRect(1480, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        self.subtitle_vertex.setFont(font)
        self.subtitle_vertex.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle_vertex.setObjectName("subtitle_vertex")
        self.workMode = QtWidgets.QLabel(self.generalWigdet)
        self.workMode.setGeometry(QtCore.QRect(70, 70, 601, 51))
        self.workMode.setObjectName("workMode")
        self.label_2 = QtWidgets.QLabel(self.generalWigdet)
        self.label_2.setGeometry(QtCore.QRect(100, 790, 191, 51))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.generalWigdet)
        self.label_4.setGeometry(QtCore.QRect(100, 870, 191, 51))
        self.label_4.setObjectName("label_4")
        self.bfs_text = QtWidgets.QLabel(self.generalWigdet)
        self.bfs_text.setGeometry(QtCore.QRect(100, 830, 601, 41))
        self.bfs_text.setObjectName("bfs_text")
        self.dfs_text = QtWidgets.QLabel(self.generalWigdet)
        self.dfs_text.setGeometry(QtCore.QRect(100, 920, 601, 41))
        self.dfs_text.setObjectName("dfs_text")
        self.label_3 = QtWidgets.QLabel(self.generalWigdet)
        self.label_3.setGeometry(QtCore.QRect(730, 790, 201, 51))
        self.label_3.setObjectName("label_3")
        self.dijkstra_text = QtWidgets.QLabel(self.generalWigdet)
        self.dijkstra_text.setGeometry(QtCore.QRect(730, 830, 461, 41))
        self.dijkstra_text.setObjectName("dijkstra_text")
        self.label_5 = QtWidgets.QLabel(self.generalWigdet)
        self.label_5.setGeometry(QtCore.QRect(1230, 770, 201, 51))
        self.label_5.setObjectName("label_5")
        self.matrix_text = QtWidgets.QLabel(self.generalWigdet)
        self.matrix_text.setGeometry(QtCore.QRect(1230, 830, 431, 141))
        self.matrix_text.setText("")
        self.matrix_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.matrix_text.setObjectName("matrix_text")
        MainWindow.setCentralWidget(self.generalWigdet)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1716, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Grafos"))
        self.cleanAll.setText(_translate("MainWindow", "Borrar Todo"))
        self.addVertex.setText(_translate("MainWindow", "Agrega vertice"))
        self.delVertex.setText(_translate("MainWindow", "Elimina vertice"))
        self.addEdge.setText(_translate("MainWindow", "Agrega conexión"))
        self.delEdge.setText(_translate("MainWindow", "Elimina conexión"))
        self.subtitle_edge.setText(_translate("MainWindow", "Conexiones"))
        self.subtitle_vertex.setText(_translate("MainWindow", "Vertices"))
        self.workMode.setText(_translate("MainWindow", "Modo de trabajo: "))
        self.label_2.setText(_translate("MainWindow", "Recorrido BFS"))
        self.label_4.setText(_translate("MainWindow", "Recorrido DFS"))
        self.bfs_text.setText(_translate("MainWindow", "[ ]"))
        self.dfs_text.setText(_translate("MainWindow", "[ ]"))
        self.label_3.setText(_translate("MainWindow", "Recorrido Dijkstra"))
        self.dijkstra_text.setText(_translate("MainWindow", "[ ]"))
        self.label_5.setText(_translate("MainWindow", "Matriz de adyecencia"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
